name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'   
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '8.0'
    - name: create database in mysql-server
      run: mysql -uroot -h127.0.0.1 < src/sql/create-p2parkingdb.sql  
    - name: compile the code
      run: mvn clean compile
    - name: Unit Tests with Maven
      run: mvn test -Dgroups="p2parking.testCategories.UnitTest"
    - name: Datanucleus enhance
      run: mvn datanucleus:enhance
    - name: Create Datanucleus schema
      run: mvn datanucleus:schema-create
    - name: Insert examples to database
      run: mvn exec:java -PinsertarEjemplos
    - name: Integration tests with Maven
      run: mvn test -Dgroups="p2parking.testCategories.IntegrationTest"
